#!/bin/bash

dw#CMD# () {

#CMD#dw_output

echo -e "\n\nEnter Input: " && read input && echo -e "\n"

#CMD#dw_output $input

unset input
}

#CMD#dw_block () {

if [ -z "$1" ] || [ "$1" = "$2" ] || [ "$1" = "a" ]
then
	echo -E "$2. $3"
fi
if [ "$1" = "$2" ] || [ "$1" = "a" ]
then
	echo -E 'eg.'
	for value in "${com[@]}"; 
	do 
	     echo -e "$value"; 
	done
	echo
fi
}

#CMD#dw_output () {

if [ -z "$1" ] 
then
	echo -e 'dw#CMD#:input\n'
else
	echo -e 'dw#CMD#:help\n'
fi

cur=1

des=''
declare -a com=(
	''
)
#CMD#dw_block "$1" "${cur}" "${des}" "${com}"
cur=$((cur+1))

}














